### PR TITLE
Added @cronco to about page.

### PR DESCRIPTION
**Pull request by stas**
@cronco please merge this if you're ok, or push changes.

### CODE REVIEW

**Comment by cronco** [comment]
Looks good to me. :+1:  In the long run I'd like to also get involved in some back-end stuff, but the blurb's good. :)

**Comment by cronco** [comment]
Looks good to me. :+1:  In the long run I'd like to also get involved in some back-end stuff, but the blurb's good. :)

**Comment by stas** [comment]
Deployed. Welcome to the band!
http://coursewa.re/about

**Comment by stas** [comment]
Btw, seriously, time to update that avatar :bow:

**Pull request merged**
